groups:
  - name: todo-assessment-alerts
    rules:

      - alert: BackendDown
        expr: up{job="todo-backend"} < 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend application is down"
          description: "The Todo Summary Assistant backend has been unavailable for at least 1 minute."

      - alert: HighEC2CPU
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "EC2 CPU usage is high"
          description: "EC2 CPU usage has remained above 80% for at least 5 minutes."